### ISSUE TITLE
フレームワーク、ライブラリ、インフラ構成の選定

### ISSUE THREAD

**Issue by yuma300** [mikimiki1212/cook_m#2]
# 本課題の目的
本課題において、最も早く簡単にcook_mを実装・公開できるのか検討し選定を行う

# 成果物
具体的なフレームワーク、ライブラリ、インフラの構成

**Comment by yuma300** [comment]
フロント側フレームワーク: Vue.js
サーバーサイド側フレームワーク: 無し
UIフレームワーク: vuematerial.io
ホスティング&httpサーバー: github pages

**Comment by yuma300** [comment]
完了

**Comment by yuma300** [comment]
@mikimiki1212 
UIフレームワークはなぜ最もポピュラーなElementではなくて、vuematerial.ioにしたのか理由の記載お願いします。

**Comment by mikimiki1212** [comment]
@yuma300
Vue MaterialはVue.jsで最も使用されているUIライブラリであり、シンプル、軽量、そしてグーグルのマテリアルデザイン仕様に従って正確に作られているからです。

**Comment by yuma300** [comment]
LGTM
